### ISSUE TITLE
LLVM.SetGC("shadow-stack") causes AccessViolationException

### ISSUE THREAD

**Issue by halivingston** [mjsabby/LLVMSharp#3] opened 2015-04-01 22:04 UTC
I've asked this on the LLVM mailing lists but have got no traction. I've even opened a bug:

https://llvm.org/bugs/show_bug.cgi?id=23095

I'm opening a bug here because it means LLVMSharp can't set gc information on a function

**Comment by mjsabby** [comment] 2015-04-01 22:35
You need to link in shadow stack GC. The problem is that they are not exposed via C bindings.

I have a review out to LLVM folks: http://reviews.llvm.org/D8788

**Comment by mjsabby** [comment] 2015-04-29 23:35
The code review is still pending, but I'm going to provide a fix for it as a wrapper on both Linux and Windows in the next release which is going to happen co-inciding with LLVM 3.6.1 (so about a week or so)

**Comment by mjsabby** [comment] 2015-08-02 20:25
I have a fix for this as part of LLVM 3.7 release

**Comment by mjsabby** [comment] 2015-08-28 07:41
This has been fixed in https://www.nuget.org/packages/LLVMSharp/3.7.0-rc4-final and beyond, the final release is due in a week.

**Comment by mjsabby** [comment] 2015-09-01 21:23
Fixed with LLVM 3.7 release: https://www.nuget.org/packages/LLVMSharp/3.7.0

**Closed by mjsabby** 2015-09-01 21:23 UTC
Labels: bug
